(function() {
  'use strict';
  var BANK = (typeof window !== 'undefined' && window.PRAXIS_INDICATOR_BANK) || {};
  var OECD_DAC = BANK.OECD_DAC || {};

  var escHtml = window.PraxisExportUtils.escHtml;
  var exportFilename = window.PraxisExportUtils.exportFilename;

  function criterionLabel(c) { return (OECD_DAC[c] && OECD_DAC[c].name) || c; }
  function indicatorText(row) {
    return (row.indicators || []).map(function(i) { return (i.code ? '[' + i.code + '] ' : '') + i.name; }).join(', ');
  }
  function sourcesText(row) { return (row.dataSources || []).join(', '); }

  // Programme identity for filenames and the provenance sheet. The matrix
  // context passed by Station 2 does not carry programme_name or organisation,
  // so fall back to the saved project in localStorage.
  function projectMeta(context) {
    var meta = { programme: (context && context.programmeName) || '', organisation: '' };
    try {
      var saved = localStorage.getItem('praxis-workbench');
      if (saved) {
        var parsed = JSON.parse(saved);
        var pm = (parsed && parsed.project_meta) || {};
        if (!meta.programme) meta.programme = pm.programme_name || '';
        meta.organisation = pm.organisation || '';
      }
    } catch (e) { /* localStorage unavailable or unparseable; keep defaults */ }
    return meta;
  }

  function exportAsWord(rows, context) {
    var meta = projectMeta(context);
    var title = meta.programme || 'Evaluation Matrix';
    var html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">' +
      '<head><meta charset="UTF-8"><style>' +
      'table{border-collapse:collapse;width:100%;font-family:Calibri,sans-serif;font-size:10pt}' +
      'th{background:#0B1A2E;color:#fff;padding:6px 8px;text-align:left;font-size:9pt}' +
      'td{border:1px solid #ccc;padding:5px 8px;vertical-align:top;font-size:10pt}' +
      'tr:nth-child(even){background:#f9f9f9}' +
      '.footer{font-size:8pt;color:#999;margin-top:20px}' +
      '</style></head><body>' +
      '<h2 style="font-family:Calibri;color:#0B1A2E">' + escHtml(title) + '</h2>' +
      '<table><tr><th>#</th><th>Criterion</th><th>Evaluation Question</th>' +
      '<th>Indicators</th><th>Data Sources</th><th>Judgement Criteria</th></tr>';

    rows.forEach(function(row, i) {
      html += '<tr>' +
        '<td>' + (i + 1) + '</td>' +
        '<td>' + escHtml(criterionLabel(row.criterion)) + '</td>' +
        '<td>' + escHtml(row.question || '') + '</td>' +
        '<td>' + escHtml(indicatorText(row)) + '</td>' +
        '<td>' + escHtml(sourcesText(row)) + '</td>' +
        '<td>' + escHtml(row.judgementCriteria || '') + '</td>' +
        '</tr>';
    });

    html += '</table><p class="footer">Generated by PRAXIS Evaluation Workbench</p></body></html>';

    var blob = new Blob([html], { type: 'application/msword' });
    PraxisUtils.downloadBlob(blob, exportFilename(meta.programme, 'evaluation-matrix', 'doc'));
  }

  // Ensure SheetJS (XLSX) is loaded before building the workbook.
  function ensureXLSX() {
    if (window.XLSX) return Promise.resolve();
    if (typeof window.loadSheetJS === 'function') return window.loadSheetJS();
    return Promise.reject(new Error('Spreadsheet library (SheetJS) is unavailable'));
  }

  // Provenance rows for the About sheet appended to spreadsheet exports.
  function aboutSheetData(meta, station) {
    return [
      ['Programme', meta.programme || 'Not specified'],
      ['Organisation', meta.organisation || 'Not specified'],
      ['Exported', new Date().toISOString()],
      ['Workbench version', (window.PraxisSchema && window.PraxisSchema.PRAXIS_VERSION) || 'unknown'],
      ['Station', station]
    ];
  }

  function exportAsExcel(rows, context) {
    var meta = projectMeta(context);
    return ensureXLSX().then(function() {
      var XLSX = window.XLSX;
      // flattenMatrixForExport dereferences id and indicators; normalise rows
      // that arrive from older .praxis files without those fields.
      var safeRows = rows.map(function(row) {
        return Object.assign({ id: '', indicators: [] }, row);
      });
      var data = MatrixGenerator.flattenMatrixForExport(safeRows);
      var ws = XLSX.utils.json_to_sheet(data);
      // Column widths: EQ #, Criterion, Question, Sub-Questions, Judgement
      // Criteria, Indicators, Data Sources, Disaggregation, Rationale.
      ws['!cols'] = [
        { wch: 8 }, { wch: 16 }, { wch: 55 }, { wch: 45 },
        { wch: 35 }, { wch: 40 }, { wch: 30 }, { wch: 25 }, { wch: 35 }
      ];
      var wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Evaluation Matrix');
      var aboutWs = XLSX.utils.aoa_to_sheet(aboutSheetData(meta, 'Station 2: Evaluation Matrix'));
      aboutWs['!cols'] = [{ wch: 20 }, { wch: 60 }];
      XLSX.utils.book_append_sheet(wb, aboutWs, 'About');
      XLSX.writeFile(wb, exportFilename(meta.programme, 'evaluation-matrix', 'xlsx'));
    });
  }

  function exportAsJSON(rows, context) {
    var meta = projectMeta(context);
    var payload = {
      schema: 'praxis-workbench',
      _partial: true,
      _station: 2,
      evaluation_matrix: {
        context: context || {},
        rows: rows,
        exported_at: new Date().toISOString()
      }
    };
    PraxisUtils.downloadJSON(payload, exportFilename(meta.programme, 'evaluation-matrix', 'praxis'));
  }

  window.MatrixExport = {
    exportAsWord: exportAsWord,
    exportAsExcel: exportAsExcel,
    exportAsJSON: exportAsJSON
  };
})();
