(function() {
  'use strict';
  var BANK = (typeof window !== 'undefined' && window.PRAXIS_INDICATOR_BANK) || {};
  var OECD_DAC = BANK.OECD_DAC || {};

  function criterionLabel(c) { return (OECD_DAC[c] && OECD_DAC[c].name) || c; }
  function indicatorText(row) {
    return (row.indicators || []).map(function(i) { return (i.code ? '[' + i.code + '] ' : '') + i.name; }).join(', ');
  }
  function sourcesText(row) { return (row.dataSources || []).join(', '); }

  function exportAsWord(rows, context) {
    var title = (context && context.programmeName) || 'Evaluation Matrix';
    var html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">' +
      '<head><meta charset="UTF-8"><style>' +
      'table{border-collapse:collapse;width:100%;font-family:Calibri,sans-serif;font-size:10pt}' +
      'th{background:#0B1A2E;color:#fff;padding:6px 8px;text-align:left;font-size:9pt}' +
      'td{border:1px solid #ccc;padding:5px 8px;vertical-align:top;font-size:10pt}' +
      'tr:nth-child(even){background:#f9f9f9}' +
      '.footer{font-size:8pt;color:#999;margin-top:20px}' +
      '</style></head><body>' +
      '<h2 style="font-family:Calibri;color:#0B1A2E">' + title + '</h2>' +
      '<table><tr><th>#</th><th>Criterion</th><th>Evaluation Question</th>' +
      '<th>Indicators</th><th>Data Sources</th><th>Judgement Criteria</th></tr>';

    rows.forEach(function(row, i) {
      html += '<tr>' +
        '<td>' + (i + 1) + '</td>' +
        '<td>' + criterionLabel(row.criterion) + '</td>' +
        '<td>' + (row.question || '') + '</td>' +
        '<td>' + indicatorText(row) + '</td>' +
        '<td>' + sourcesText(row) + '</td>' +
        '<td>' + (row.judgementCriteria || '') + '</td>' +
        '</tr>';
    });

    html += '</table><p class="footer">Generated by PRAXIS Evaluation Workbench</p></body></html>';

    var blob = new Blob([html], { type: 'application/msword' });
    PraxisUtils.downloadBlob(blob, 'evaluation-matrix.doc');
  }

  function exportAsExcel(rows, context) {
    if (typeof XLSX === 'undefined') { alert('SheetJS not loaded'); return; }
    var data = rows.map(function(row, i) {
      return {
        '#': i + 1,
        'Criterion': criterionLabel(row.criterion),
        'Evaluation Question': row.question || '',
        'Indicators': indicatorText(row),
        'Data Sources': sourcesText(row),
        'Judgement Criteria': row.judgementCriteria || ''
      };
    });
    var ws = XLSX.utils.json_to_sheet(data);
    // Column widths
    ws['!cols'] = [{ wch: 4 }, { wch: 14 }, { wch: 55 }, { wch: 30 }, { wch: 25 }, { wch: 30 }];
    var wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Evaluation Matrix');
    XLSX.writeFile(wb, 'evaluation-matrix.xlsx');
  }

  function exportAsJSON(rows, context) {
    var payload = {
      schema: 'praxis-workbench',
      _partial: true,
      _station: 2,
      evaluation_matrix: {
        context: context || {},
        rows: rows,
        exported_at: new Date().toISOString()
      }
    };
    PraxisUtils.downloadJSON(payload, 'evaluation-matrix.praxis');
  }

  window.MatrixExport = {
    exportAsWord: exportAsWord,
    exportAsExcel: exportAsExcel,
    exportAsJSON: exportAsJSON
  };
})();
